---
id: commerce
version: '1.0'
name: E commerce workflow
start: ProcessOrder
functions:
- name: orderNew
  type: custom
  operation: "rest:post:/"
- name: payment
  type: custom
  operation: "rest:post:/"
- name: inventoryReserve
  type: custom
  operation: "rest:post:/"
- name: success
  type: custom
  operation: "rest:post:/"
- name: orderUpdate
  type: custom
  operation: "rest:post:/"
- name: failure
  type: custom
  operation: "rest:post:/"
errors:
- name: failure processing order
  code: 400 
states:
- name: ProcessOrder
  type: operation
  actions:
  - functionRef:
      refName: orderNew
  transition: ProcessPayment
  compensatedBy: UpdateOrderStatus
  onErrors:
  - errorRef: failure processing order
    transition: ServiceError
- name: ProcessPayment
  type: operation
  actions:
  - functionRef:
      refName: payment
  transition: ReserveInventory
- name: ReserveInventory
  type: operation
  actions:
  - functionRef:
      refName: inventoryReserve
  transition: Success
- name: Success
  type: operation
  actions:
  - functionRef:
      refName: success
  end: true
- name: UpdateOrderStatus
  type: operation
  usedForCompensation: true
  actions:
  - functionRef:
      refName: orderUpdate
- name: ServiceError
  type: inject
  data: {}
  transition:
    nextState: Failure
    compensate: true
- name: Failure
  type: operation
  actions:
  - functionRef:
      refName: failure
  end: true